### ISSUE TITLE
Segfalt

### ISSUE THREAD

**Issue by tremby** [EionRobb/pidgin-pushbullet#7]
Just had another segfault, which I don't think is related to the other.

At the time when I ran this code, the line 154 which it references is the `conn->callback(conn->pba, root, conn->user_data);` line in the `else` clause of `pb_response_callback`.

I wasn't doing anything in particular at this point, but it was quite soon after starting Pidgin.

It's possible of course I've caused this with my code changes, but as far as I can tell nothing I've done should affect this.

```
(gdb) run
Starting program: /usr/bin/pidgin 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe17a9700 (LWP 24895)]
[New Thread 0x7fffc684e700 (LWP 24898)]
[New Thread 0x7fffc5a83700 (LWP 24899)]
[New Thread 0x7fffc5282700 (LWP 24900)]
[New Thread 0x7fffc4a81700 (LWP 24901)]
Traceback (most recent call last):
  File "/usr/share/gdb/auto-load/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.19-gdb.py", line 63, in <module>
    from libstdcxx.v6.printers import register_libstdcxx_printers
ImportError: No module named 'libstdcxx'
[Thread 0x7fffc5282700 (LWP 24900) exited]
[Thread 0x7fffc4a81700 (LWP 24901) exited]

Program received signal SIGSEGV, Segmentation fault.
__strcmp_sse2_unaligned () at ../sysdeps/x86_64/multiarch/strcmp-sse2-unaligned.S:29
29  ../sysdeps/x86_64/multiarch/strcmp-sse2-unaligned.S: No such file or directory.
(gdb) bt
#0  __strcmp_sse2_unaligned () at ../sysdeps/x86_64/multiarch/strcmp-sse2-unaligned.S:29
#1  0x00007ffff559cfc9 in g_str_equal () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007fffedcede61 in pb_set_base64_icon_for_buddy (buddy=0x5555562ede90, 
    base64_icon=0x555557c98e30 "/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcU\nFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgo\nKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKC"...) at libpushbullet.c:120
#3  pb_got_phone_threads (pba=0x555555ea20c0, node=<optimized out>, user_data=0x555557ca9f40) at libpushbullet.c:622
#4  0x00007fffedced890 in pb_response_callback (url_data=<optimized out>, user_data=0x5555569fca90, 
    url_text=0x5555576aa3e0 "{\"key\":\"ujEuSe57Vu0sjAnBdJA0yG_threads\",\"data\":{\"threads\":[{\"id\":\"4\",\"recipients\":[{\"name\":\"Bob McCallan\",\"address\":\"+1 555-555-5555\",\"number\":\"+1 555-555-5555\",\"thumbnail\":\"\\/9j\\/4AAQSkZJRgABAQAAAQAB"..., len=<optimized out>, error_message=<optimized out>) at libpushbullet.c:154
#5  0x00007ffff52d8651 in ?? () from /usr/lib/libpurple.so.0
#6  0x00005555555c8a5e in ?? ()
#7  0x00007ffff55acce5 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#8  0x00007ffff55ad048 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#9  0x00007ffff55ad30a in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#10 0x00007ffff6835447 in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#11 0x000055555558f8f3 in main ()
(gdb) bt full
#0  __strcmp_sse2_unaligned () at ../sysdeps/x86_64/multiarch/strcmp-sse2-unaligned.S:29
No locals.
#1  0x00007ffff559cfc9 in g_str_equal () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007fffedcede61 in pb_set_base64_icon_for_buddy (buddy=0x5555562ede90, 
    base64_icon=0x555557c98e30 "/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcU\nFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgo\nKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKC"...) at libpushbullet.c:120
        icon_data = <optimized out>
        icon_len = 140737187453535
        checksum = 0x555556f65360 "3466199746d"
        old_checksum = 0x0
#3  pb_got_phone_threads (pba=0x555555ea20c0, node=<optimized out>, user_data=0x555557ca9f40) at libpushbullet.c:622
        first_recipient = <optimized out>
        thread = 0x555556cfe6e0
        id = 0x5555570f1aa0 "4"
        recipients = <optimized out>
        from = 0x555555d314f0 "+1 555-555-5555"
        account = 0x555555ad95c0
        rootobj = <optimized out>
        data = <optimized out>
        threads = 0x5555562a78c0
        i = 0
        len = 6
        device = 0x555557ca9f40 "ujEuSe57Vu0sjAnBdJA0yG"
        last_message_timestamp = 1440460880
        newest_phone_message_id = 0
#4  0x00007fffedced890 in pb_response_callback (url_data=<optimized out>, user_data=0x5555569fca90, 
    url_text=0x5555576aa3e0 "{\"key\":\"ujEuSe57Vu0sjAnBdJA0yG_threads\",\"data\":{\"threads\":[{\"id\":\"4\",\"recipients\":[{\"name\":\"Bob McCallan\",\"address\":\"+1 555-555-5555\",\"number\":\"+1 555-555-5555\",\"thumbnail\":\"\\/9j\\/4AAQSkZJRgABAQAAAQAB"..., len=<optimized out>, error_message=<optimized out>) at libpushbullet.c:154
        root = 0x555556c906a0
        conn = 0x5555569fca90
        parser = 0x55555702e6e0
#5  0x00007ffff52d8651 in ?? () from /usr/lib/libpurple.so.0
No symbol table info available.
#6  0x00005555555c8a5e in ?? ()
No symbol table info available.
#7  0x00007ffff55acce5 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#8  0x00007ffff55ad048 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#9  0x00007ffff55ad30a in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#10 0x00007ffff6835447 in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
No symbol table info available.
#11 0x000055555558f8f3 in main ()
No symbol table info available.
(gdb)
```

**Comment by EionRobb** [comment]
That's looking like the exact same crash, on line 120 :) 

Sorry I'm not able to help out as quickly as I would normally be able to while I'm in hospital. 

Hopefully you've had some successes from other changes, as mentioned in the other issue. Let's continue the conversation there :)

**Comment by tremby** [comment]
Oh yeah! Oops! :)
