### ISSUE TITLE
Segmentation Fault when adding account. 

### ISSUE THREAD

**Issue by jarredkenny** [EionRobb/pidgin-pushbullet#8]
Hello, 

I am trying to get pidgin-pushbullet working and was able to complie the plugin without any issues. However, when I attempt to add my pushbullet account within pidgin, pidgin crashes. 

When running pidgin with the -d flag, I see the following debug data.

http://paste.ubuntu.com/12799575/

The relevant error messages seem to be: 

```
(Pidgin:18488): Json-CRITICAL **: json_object_get_string_member: assertion 'node != NULL' failed

(Pidgin:18488): Json-CRITICAL **: json_object_get_string_member: assertion 'node != NULL' failed
dns[18506]: Oops, father has gone, wait for me, wait...!
[1]    18488 segmentation fault (core dumped)  pidgin -d
dns[18504]: Oops, father has gone, wait for me, wait...!
```

Any help you can provide in getting this working would be greatly appreciated.

**Comment by EionRobb** [comment]
Are you able to get a backtrace to help track down the crash? https://developer.pidgin.im/wiki/GetABacktrace

**Comment by mlopezgva** [comment]
Got something similar... But algo a very strange message. But then, I don't know if it's related to this plugin.

~~The `make` raised some warnings and an error witha png icon, which I dismissed...~~

[EDITED]
Errors with icons solved after I created an `icons/` subdir and moved'em there. Recommend doing the same or update the Makefile...

In fact, after doing a `pidgin -d` start, I saw that it works... connects, authenticates, retrieves a 1Gb JSON stream... :D, and then... stops. Completely. Pigdin shuts down. If I delete the account data (`accounts.xml`) the rest is absolutely normal.

```
(Pidgin:21990): Json-CRITICAL **: json_object_get_boolean_member: assertion `node != NULL' failed
(14:53:45) pushbullet: Fetching url https://api.pushbullet.com/v2/permanents/phonebook_uju896DVKHAsjAzT8OzbmC?
(14:53:45) util: requesting to fetch a URL
(14:53:45) dnsquery: Performing DNS lookup for api.pushbullet.com

(Pidgin:21990): Json-CRITICAL **: json_object_get_string_member: assertion `node != NULL' failed

(Pidgin:21990): Json-CRITICAL **: json_object_get_string_member: assertion `node != NULL' failed

(Pidgin:21990): Json-CRITICAL **: json_object_get_string_member: assertion `node != NULL' failed
(14:53:45) gtkconv: setting active conversation on toolbar 0x224c9180
(14:53:45) gtkconv: setting active conversation on toolbar 0x224c9180
(14:53:45) prefs: /pidgin/conversations/toolbar/wide changed, scheduling save.
(14:53:45) log: Failed to open log file "/home/manuel/.purple/logs/nicamlg@gmail.com.log" for reading: No existe el archivo o el directorio
(14:53:45) Trillian log list: Reading /mnt/windows/Program Files/Trillian/users/default/logs/PUSHBULLET/nicamlg@gmail.com.log
(14:53:45) Trillian log list: Reading /mnt/windows/Program Files/Trillian/users/default/logs/PUSHBULLET/Query/nicamlg@gmail.com.log
(14:53:45) util: requesting to fetch a URL
(14:53:45) dnsquery: Performing DNS lookup for s3.amazonaws.com
dns[22002]: Oops, father has gone, wait for me, wait...!
Violación de segmento (`core' generado)
dns[22001]: Oops, father has gone, wait for me, wait...!
dns[22000]: Oops, father has gone, wait for me, wait...!
dns[21999]: Oops, father has gone, wait for me, wait...!
```

**Comment by EionRobb** [comment]
1gb? :O 
Blimey

Do you also happen to have a backtrace of the crash?

**Comment by mlopezgva** [comment]
The 1Gb part was a joke, obviously. :D It's just that I have never seen the resonse of any requests to the pushbullet API.. :wink:

Well, no, I don't have the crash dump. I'll try to get one tonight, but I'm using pidgin right now (faculty team project) and can't stop it right now. :) Ill send you one ASAP.

**Comment by EionRobb** [comment]
Dumpy dump dump plzkthx? :)

**Comment by synthead** [comment]
I am encountering the same issue and have created a backtrace as per [these instructions](https://developer.pidgin.im/wiki/GetABacktrace#TheEasyWay):

```
GNU gdb (GDB) 7.11
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from pidgin...(no debugging symbols found)...done.
(gdb) handle SIGPIPE nostop noprint
Signal        Stop  Print   Pass to program Description
SIGPIPE       No    No  Yes     Broken pipe
(gdb) run
Starting program: /usr/bin/pidgin 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffd9861700 (LWP 8641)]
[New Thread 0x7fffd9060700 (LWP 8642)]

(Pidgin:8635): Json-CRITICAL **: json_object_get_array_member: assertion 'node != NULL' failed

(Pidgin:8635): Json-CRITICAL **: json_array_get_length: assertion 'array != NULL' failed

(Pidgin:8635): Json-CRITICAL **: json_object_get_string_member: assertion 'node != NULL' failed

(Pidgin:8635): Json-CRITICAL **: json_object_get_string_member: assertion 'node != NULL' failed

(Pidgin:8635): Json-CRITICAL **: json_object_get_string_member: assertion 'node != NULL' failed

(Pidgin:8635): Json-CRITICAL **: json_object_get_string_member: assertion 'node != NULL' failed

(Pidgin:8635): Json-CRITICAL **: json_object_get_string_member: assertion 'node != NULL' failed

(Pidgin:8635): Json-CRITICAL **: json_object_get_string_member: assertion 'node != NULL' failed

(Pidgin:8635): Json-CRITICAL **: json_object_get_string_member: assertion 'node != NULL' failed

(Pidgin:8635): Json-CRITICAL **: json_object_get_string_member: assertion 'node != NULL' failed

(Pidgin:8635): Json-CRITICAL **: json_object_get_string_member: assertion 'node != NULL' failed

(Pidgin:8635): Json-CRITICAL **: json_object_get_string_member: assertion 'node != NULL' failed

(Pidgin:8635): Json-CRITICAL **: json_object_get_array_member: assertion 'node != NULL' failed

(Pidgin:8635): Json-CRITICAL **: json_array_get_length: assertion 'array != NULL' failed

(Pidgin:8635): Json-CRITICAL **: json_object_get_int_member: assertion 'node != NULL' failed

Thread 1 "pidgin" received signal SIGSEGV, Segmentation fault.
0x00007ffff51d21dd in purple_account_get_int () from /usr/lib/libpurple.so.0
(gdb) bt full
#0  0x00007ffff51d21dd in purple_account_get_int () from /usr/lib/libpurple.so.0
No symbol table info available.
#1  0x00007fffdc42af2b in ?? () from /usr/lib/purple-2/libpushbullet.so
No symbol table info available.
#2  0x00007fffdc4297a0 in ?? () from /usr/lib/purple-2/libpushbullet.so
No symbol table info available.
#3  0x00007ffff52358dd in ?? () from /usr/lib/libpurple.so.0
No symbol table info available.
#4  0x000000000046990e in ?? ()
No symbol table info available.
#5  0x00007ffff5514dba in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
No symbol table info available.
#6  0x00007ffff5515160 in ?? () from /usr/lib/libglib-2.0.so.0
No symbol table info available.
#7  0x00007ffff5515482 in g_main_loop_run () from /usr/lib/libglib-2.0.so.0
No symbol table info available.
#8  0x00007ffff67d94e7 in gtk_main () from /usr/lib/libgtk-x11-2.0.so.0
No symbol table info available.
#9  0x0000000000431f19 in main ()
No symbol table info available.
(gdb) quit
A debugging session is active.

    Inferior 1 [process 8635] will be killed.

Quit anyway? (y or n) y
```

**Comment by tubaman** [comment]
Here's a better backtrace @EionRobb :

```
#0  purple_account_get_int (account=0x150540000e014, 
    name=name@entry=0x7fffe08ffa68 "last_message_timestamp", 
    default_value=default_value@entry=0)
    at /build/pidgin-2.11.0/./libpurple/account.c:2491
#1  0x00007fffe08feacb in pb_got_everything (pba=0x55555648f770, 
    node=<optimized out>, user_data=<optimized out>) at libpushbullet.c:820
#2  0x00007fffe08fd700 in pb_response_callback (url_data=<optimized out>, 
    user_data=0x5555565546f0, 
    url_text=0x5555565531b0 "{\"accounts\":[],\"blocks\":[],\"channels\":[],\"chats\":[{\"active\":true,\"iden\":\"ujxJXqSxM8ysjAnBdJA0yG\",\"created\":1.4465827960258229e+09,\"modified\":1.4465827960258298e+09,\"with\":{\"type\":\"email\",\"email\":\"gary"..., len=<optimized out>, error_message=<optimized out>)
    at libpushbullet.c:150
#3  0x00007ffff524d21d in url_fetch_recv_cb (url_data=0x555556526aa0, 
    source=<optimized out>, cond=<optimized out>)
    at /build/pidgin-2.11.0/./libpurple/util.c:3996
#4  0x00005555555c5e0e in pidgin_io_invoke (source=<optimized out>, 
    condition=<optimized out>, data=0x55555652dcb0)
    at /build/pidgin-2.11.0/./pidgin/gtkeventloop.c:73
#5  0x00007ffff552ceaa in g_main_context_dispatch ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#6  0x00007ffff552d260 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#7  0x00007ffff552d582 in g_main_loop_run ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#8  0x00007ffff67d3567 in gtk_main ()
   from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#9  0x000055555558c377 in main (argc=2, argv=0x7fffffffe1a8)
    at /build/pidgin-2.11.0/./pidgin/gtkmain.c:937
```
